settings:
  ci: false
  # appDataDir: /Users/opendersingh/Library/Application Support/Insomnia Designer
  env: UnitTest
  bail: true
scripts:
  lint: lint spec "Designer Demo"

  test: run test "Designer Demo"
  test:200s: test --test-name-pattern 200
  test:404s: test --test-name-pattern 404
  test:suite:math: run test uts_8783c30a24b24e9a851d96cce48bd1f2
  test:suite:requests: run test uts_bce4af
  
  gen-conf: generate config "Designer Demo" --type declarative
  gen-conf:k8s: gen-conf --type kubernetes
